INSERT INTO "PLAYER" (NAME, POSITION, HEIGHT) VALUES('Michael Jordan', 'SG', 6.4);
INSERT INTO "PLAYER" (NAME, POSITION, HEIGHT) VALUES('Larry Bird', 'SF', 6.7);
INSERT INTO "PLAYER" (NAME, POSITION, HEIGHT) VALUES('Shaqulle Oneal', 'C', 7.1);